# Generated by Django 5.2.8 on 2025-11-25 09:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_years', models.PositiveSmallIntegerField(verbose_name='Xidmət etdiyiniz il')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Ünvan')),
                ('phone', models.CharField(max_length=50, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('instagram', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
                ('linkedn', models.URLField(blank=True, null=True)),
                ('tiktok', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Əlaqə',
                'verbose_name_plural': 'Əlaqələr',
            },
        ),
        migrations.CreateModel(
            name='Motto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Devizlər',
            },
        ),
        migrations.CreateModel(
            name='SaleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale', models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Endirim faizi')),
                ('min_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Endirimin aktif olacağı dəyər')),
                ('active', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Endirim kampaniyası',
                'verbose_name_plural': 'Endirim kampaniyaları',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Qiymət')),
                ('vip_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='VIP Qiymət')),
                ('premium_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Premium Qiymət')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Video')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Url')),
                ('is_vip', models.BooleanField(blank=True, default=False, null=True, verbose_name='Vip')),
                ('is_premium', models.BooleanField(blank=True, default=False, null=True, verbose_name='Premium')),
                ('measure_type', models.CharField(choices=[('m', 'm'), ('m2', 'm2'), ('kg', 'kg'), ('ədəd', 'ədəd')], max_length=10, verbose_name='Ölçü Növü')),
                ('delivery', models.BooleanField(blank=True, default=False, null=True, verbose_name='Çatdırılma')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='Servis aktivliyi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Servis yaradılma tarixi')),
            ],
            options={
                'verbose_name': 'Servis',
                'verbose_name_plural': 'Servislər',
            },
        ),
        migrations.CreateModel(
            name='SpecialProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Url')),
                ('is_active', models.BooleanField(blank=True, default=False, null=True, verbose_name='Lahiyə aktivliyi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Lahiyə yaradılma tarixi')),
            ],
            options={
                'verbose_name': 'Xüsusi Lahiyə',
                'verbose_name_plural': 'Xüsusi Lahiyələr',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Statistika',
                'verbose_name_plural': 'Statistikalar',
            },
        ),
        migrations.CreateModel(
            name='AboutTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(validators=[django.core.validators.MaxLengthValidator(2000)], verbose_name='Servis haqqında')),
                ('languages', models.CharField(choices=[('az', 'az'), ('ru', 'ru')], max_length=12, verbose_name='Dil')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='services.about', verbose_name='Haqqımızda')),
            ],
            options={
                'verbose_name': 'Haqqımızda tərcümələri',
            },
        ),
        migrations.CreateModel(
            name='MottoTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(validators=[django.core.validators.MaxLengthValidator(2000)], verbose_name='Deviz cümləsi')),
                ('languages', models.CharField(choices=[('az', 'az'), ('ru', 'ru')], max_length=12, verbose_name='Dil')),
                ('motto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='services.motto', verbose_name='Deviz')),
            ],
            options={
                'verbose_name': 'Deviz tərcümələri',
            },
        ),
        migrations.CreateModel(
            name='SaleEventTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languages', models.CharField(blank=True, choices=[('az', 'az'), ('ru', 'ru')], max_length=12, null=True, verbose_name='Dillər')),
                ('name', models.CharField(max_length=50, verbose_name='Aksiya Adı')),
                ('description', models.TextField(validators=[django.core.validators.MaxLengthValidator(350)], verbose_name='Aksiya haqqında')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='services.saleevent', verbose_name='Endirim eventi')),
            ],
            options={
                'verbose_name': 'Endirim kampaniyası təcüməsi',
                'verbose_name_plural': 'Endirim kampaniyaları tərcümələri',
            },
        ),
        migrations.AddField(
            model_name='saleevent',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='services.service', verbose_name='Servis'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=32, verbose_name='Ad soyad')),
                ('phone_number', models.CharField(max_length=12, verbose_name='Mobil nömrə')),
                ('text', models.TextField(validators=[django.core.validators.MaxLengthValidator(140)], verbose_name='Mesaj')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Rəyin təsdiqlənməsi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Rəyin yaradılma tarixi')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='services.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Rəy',
                'verbose_name_plural': 'Rəylər',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=32, verbose_name='Ad soyad')),
                ('phone_number', models.CharField(max_length=12, verbose_name='Mobil nömrə')),
                ('text', models.TextField(validators=[django.core.validators.MaxLengthValidator(2000)], verbose_name='Mesaj')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sifarişin verilmə tarixi')),
                ('is_read', models.BooleanField(default=False, verbose_name='Oxunub')),
                ('services', models.ManyToManyField(to='services.service', verbose_name='Şifariş verilən servislər')),
            ],
            options={
                'verbose_name': 'Sifariş',
                'verbose_name_plural': 'Sifarişlər',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ServiceTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True, verbose_name='Slug')),
                ('languages', models.CharField(choices=[('az', 'az'), ('ru', 'ru')], max_length=12)),
                ('name', models.CharField(max_length=250, verbose_name='Ad')),
                ('description', models.TextField(validators=[django.core.validators.MaxLengthValidator(2000)], verbose_name='Servis haqqında')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='services.service', verbose_name='Servis')),
            ],
            options={
                'verbose_name': 'Servis tərcüməsi',
                'verbose_name_plural': 'Servis tərcümələri',
            },
        ),
        migrations.CreateModel(
            name='ServiceVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Qiymət')),
                ('vip_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='VIP Qiymət ')),
                ('premium_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Premium Qiymət')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='services.service', verbose_name='Servis üçün növlər')),
            ],
            options={
                'verbose_name': 'Servis növü',
                'verbose_name_plural': 'Servis növləri',
            },
        ),
        migrations.CreateModel(
            name='ServiceVariantTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languages', models.CharField(blank=True, choices=[('az', 'az'), ('ru', 'ru')], max_length=12, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Növ adı')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='services.servicevariant', verbose_name='Növ')),
            ],
            options={
                'verbose_name': 'Növ ad tərcüməsi',
                'verbose_name_plural': 'Növ ad tərcümələri',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Şəkil')),
                ('is_home_page_background_image', models.BooleanField(default=False, verbose_name='Ana sehifesi üçün arxa plan şəkli')),
                ('is_about_page_background_image', models.BooleanField(default=False, verbose_name='Haqqımızda sehifesi üçün arxa plan şəkli')),
                ('is_calculator_page_background_image', models.BooleanField(default=False, verbose_name='Calculator sehifesi üçün arxa plan şəkli')),
                ('is_review_page_background_image', models.BooleanField(default=False, verbose_name='Comment elave et sehifesi üçün arxa plan şəkli')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Image yaradılma tarixi')),
                ('about', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='services.about', verbose_name='About')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='services.service', verbose_name='Servis')),
                ('special_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='services.specialproject', verbose_name='Xüsusi lahiyə')),
            ],
            options={
                'verbose_name': 'Şəkil',
                'verbose_name_plural': 'Şəkillər',
            },
        ),
        migrations.CreateModel(
            name='SpecialProjectTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languages', models.CharField(choices=[('az', 'az'), ('ru', 'ru')], max_length=12, verbose_name='Dil')),
                ('description', models.CharField(max_length=350, validators=[django.core.validators.MaxLengthValidator(2000)], verbose_name='Xüsusi layihə haqqında məlumat')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='services.specialproject', verbose_name='Xüsusi layihə')),
            ],
            options={
                'verbose_name': 'Xüsusi layihə tərcüməsi',
                'verbose_name_plural': 'Xüsusi layihə tərcümələri',
            },
        ),
        migrations.CreateModel(
            name='StatisticTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Statistikanın adı')),
                ('value', models.PositiveIntegerField(verbose_name='Dəyəri')),
                ('language', models.CharField(choices=[('az', 'az'), ('ru', 'ru')], max_length=12, verbose_name='Dil')),
                ('statistic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='services.statistic', verbose_name='Statistika')),
            ],
            options={
                'verbose_name': 'Statistika tərcüməsi',
                'verbose_name_plural': 'Statistika tərcümələri',
            },
        ),
    ]
