# Generated by Django 5.2.7 on 2025-11-07 18:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about-image/', verbose_name='Haqqımızda arxa plan şəkili')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=32, verbose_name='Ad soyad')),
                ('phone_number', models.CharField(max_length=12, verbose_name='Mobil nömrə')),
                ('text', models.TextField(validators=[django.core.validators.MaxLengthValidator(2000)], verbose_name='Mesaj')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Rəyin təsdiqlənməsi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Rəyin yaradılma tarixi')),
            ],
            options={
                'verbose_name': 'Rəy',
                'verbose_name_plural': 'Rəylər',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Qiymət')),
                ('vip_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='VIP Qiymət')),
                ('premium_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Premium Qiymət')),
                ('sale', models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Endirim')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Video')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Url')),
                ('is_vip', models.BooleanField(blank=True, default=False, null=True, verbose_name='Vip')),
                ('is_premium', models.BooleanField(blank=True, default=False, null=True, verbose_name='Premium')),
                ('is_number', models.BooleanField(blank=True, default=False, null=True, verbose_name='Ədəd ilə hesablanırsa')),
                ('is_kq', models.BooleanField(blank=True, default=False, null=True, verbose_name='KQ ilə hesablanırsa')),
                ('is_kv_metr', models.BooleanField(blank=True, default=False, null=True, verbose_name='Kvadrat metr (m²) ilə hesablanırsa')),
                ('is_metr', models.BooleanField(blank=True, default=False, null=True, verbose_name='Metr (m) ilə hesablanırsa')),
                ('delivery', models.BooleanField(blank=True, default=False, null=True, verbose_name='Çatdırılma')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='Servis aktivliyi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Servis yaradılma tarixi')),
            ],
            options={
                'verbose_name': 'Servis',
                'verbose_name_plural': 'Servislər',
            },
        ),
        migrations.CreateModel(
            name='SpecialProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Url')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='Servis aktivliyi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Servis yaradılma tarixi')),
            ],
            options={
                'verbose_name': 'Xüsusi Lahiyə',
                'verbose_name_plural': 'Xüsusi Lahiyələr',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_count', models.IntegerField(blank=True, null=True, verbose_name='Client sayı')),
                ('work_done_count', models.IntegerField(blank=True, null=True, verbose_name='Görülmüş iş sayı')),
                ('staff_count', models.IntegerField(blank=True, null=True, verbose_name='İşçi sayı')),
                ('achievement_count', models.IntegerField(blank=True, null=True, verbose_name='Nailiyyət sayı')),
            ],
            options={
                'verbose_name': 'Statistika',
                'verbose_name_plural': 'Statistikalar',
            },
        ),
        migrations.CreateModel(
            name='AboutTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(validators=[django.core.validators.MaxLengthValidator(2000)], verbose_name='Servis haqqında')),
                ('languages', models.CharField(choices=[('az', 'az'), ('ru', 'ru')], max_length=12, verbose_name='Dil')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='services.about', verbose_name='Haqqımızda')),
            ],
            options={
                'verbose_name': 'Haqqımızda tərcümələri',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=32, verbose_name='Ad soyad')),
                ('phone_number', models.CharField(max_length=12, verbose_name='Mobil nömrə')),
                ('text', models.TextField(validators=[django.core.validators.MaxLengthValidator(2000)], verbose_name='Mesaj')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sifarişin verilmə tarixi')),
                ('services', models.ManyToManyField(to='services.service', verbose_name='Şifariş verilən servislər')),
            ],
            options={
                'verbose_name': 'Sifariş',
                'verbose_name_plural': 'Sifarişlər',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ServiceTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True, verbose_name='Slug')),
                ('languages', models.CharField(choices=[('az', 'az'), ('ru', 'ru')], max_length=12)),
                ('name', models.CharField(max_length=250, verbose_name='Ad')),
                ('description', models.TextField(validators=[django.core.validators.MaxLengthValidator(2000)], verbose_name='Servis haqqında')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='services.service', verbose_name='Servis')),
            ],
            options={
                'verbose_name': 'Servis tərcüməsi',
                'verbose_name_plural': 'Servis tərcümələri',
            },
        ),
        migrations.CreateModel(
            name='ServiceVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Qiymət')),
                ('vip_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='VIP Qiymət ')),
                ('premium_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Premium Qiymət')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='services.service', verbose_name='Servis üçün növlər')),
            ],
            options={
                'verbose_name': 'Servis növü',
                'verbose_name_plural': 'Servis növləri',
            },
        ),
        migrations.CreateModel(
            name='ServiceVariantTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languages', models.CharField(blank=True, choices=[('az', 'az'), ('ru', 'ru')], max_length=12, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Növ adı')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='services.servicevariant', verbose_name='Növ')),
            ],
            options={
                'verbose_name': 'Növ ad tərcüməsi',
                'verbose_name_plural': 'Növ ad tərcümələri',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Şəkil')),
                ('image_name', models.CharField(max_length=50, verbose_name='Şəkil adı')),
                ('is_background_image', models.BooleanField(default=False, verbose_name='Sayt üçün arxa plan şəkli')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Image yaradılma tarixi')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='services.service', verbose_name='Servis')),
                ('special_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='services.specialproject', verbose_name='Xüsusi lahiyə')),
            ],
            options={
                'verbose_name': 'Şəkil',
                'verbose_name_plural': 'Şəkillər',
            },
        ),
        migrations.CreateModel(
            name='SpecialProjectTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languages', models.CharField(choices=[('az', 'az'), ('ru', 'ru')], max_length=12, verbose_name='Dil')),
                ('description', models.CharField(max_length=350, validators=[django.core.validators.MaxLengthValidator(2000)], verbose_name='Xüsusi layihə haqqında məlumat')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='services.specialproject', verbose_name='Xüsusi layihə')),
            ],
            options={
                'verbose_name': 'Xüsusi layihə tərcüməsi',
                'verbose_name_plural': 'Xüsusi layihə tərcümələri',
            },
        ),
    ]
