# Generated by Django 5.2.7 on 2025-11-03 17:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Qiymət')),
                ('sale', models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Endirim')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Video')),
                ('is_vip', models.BooleanField(blank=True, default=False, null=True, verbose_name='Vip')),
                ('is_premium', models.BooleanField(blank=True, default=False, null=True, verbose_name='Premium')),
                ('delivery', models.BooleanField(blank=True, default=False, null=True, verbose_name='Çatdırılma')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='Servis aktivliyi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Servis yaradılma tarixi')),
            ],
            options={
                'verbose_name': 'Məhsul',
                'verbose_name_plural': 'Məhsullar',
            },
        ),
        migrations.CreateModel(
            name='ServiceTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True, verbose_name='Slug')),
                ('language', models.CharField(choices=[('Azərbaycan', 'Azərbaycan'), ('Русский', 'Русский')], max_length=12)),
                ('name', models.CharField(max_length=250, verbose_name='Ad')),
                ('description', models.TextField(validators=[django.core.validators.MaxLengthValidator(2000)], verbose_name='Servis haqqında')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='services.service', verbose_name='Servis')),
            ],
            options={
                'verbose_name': 'Servis Tərcüməsi',
                'verbose_name_plural': 'Servis Tərcümələri',
            },
        ),
    ]
