# Generated by Django 5.2.7 on 2025-11-03 19:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Url')),
            ],
            options={
                'verbose_name': 'Xüsusi Lahiyə',
                'verbose_name_plural': 'Xüsusi Lahiyələr',
            },
        ),
        migrations.AlterModelOptions(
            name='servicetranslation',
            options={'verbose_name': 'Servis tərcüməsi', 'verbose_name_plural': 'Servis tərcümələri'},
        ),
        migrations.AddField(
            model_name='service',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Url'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Şəkil')),
                ('image_name', models.CharField(max_length=50, verbose_name='Şəkil adı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Image yaradılma tarixi')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='services.service', verbose_name='Servis')),
                ('special_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='services.specialproject', verbose_name='Xüsusi lahiyə')),
            ],
            options={
                'verbose_name': 'Şəkil',
                'verbose_name_plural': 'Şəkillər',
            },
        ),
        migrations.CreateModel(
            name='SpecialProjectTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('Azərbaycan', 'Azərbaycan'), ('Русский', 'Русский')], max_length=12, verbose_name='Dil')),
                ('description', models.CharField(max_length=350, validators=[django.core.validators.MaxLengthValidator(350)], verbose_name='Xüsusi layihə haqqında məlumat')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='services.specialproject', verbose_name='Xüsusi layihə')),
            ],
            options={
                'verbose_name': 'Xüsusi layihə tərcüməsi',
                'verbose_name_plural': 'Xüsusi layihə tərcümələri',
            },
        ),
    ]
