# Generated by Django 5.2.7 on 2025-11-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='experience_years',
            field=models.PositiveSmallIntegerField(default=25, verbose_name='Xidmət etdiyiniz il'),
            preserve_default=False,
        ),
    ]
