# Generated by Django 5.2.8 on 2025-11-15 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleevent',
            name='service',
        ),
        migrations.AlterField(
            model_name='specialproject',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Lahiyə aktivliyi'),
        ),
        migrations.AddField(
            model_name='saleevent',
            name='service',
            field=models.ManyToManyField(related_name='sales', to='services.service', verbose_name='Servis'),
        ),
    ]
