# Generated by Django 5.2.7 on 2025-11-11 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialproject',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='specialproject',
            name='is_contiune',
        ),
    ]
