# Generated by Django 5.2.7 on 2025-11-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_number',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Ədəd ilə hesablanırsa'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_kv_metr',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Kvadrat metr (m²) ilə hesablanırsa'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_metr',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Metr (m) ilə hesablanırsa'),
        ),
    ]
