# Generated by Django 5.2.8 on 2025-11-25 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'Haqqımızda', 'verbose_name_plural': 'Haqqımızda'},
        ),
        migrations.AlterModelOptions(
            name='abouttranslation',
            options={'verbose_name': 'Haqqımızda tərcüməsi', 'verbose_name_plural': 'Haqqımızda tərcümələri'},
        ),
        migrations.AlterModelOptions(
            name='motto',
            options={'verbose_name': 'Deviz', 'verbose_name_plural': 'Devizlər'},
        ),
        migrations.AddField(
            model_name='order',
            name='is_customer',
            field=models.BooleanField(default=False, verbose_name='Müştəridirmi'),
        ),
    ]
