# Generated by Django 5.2.7 on 2025-11-08 14:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MottoTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(validators=[django.core.validators.MaxLengthValidator(2000)], verbose_name='Deviz cümləsi')),
                ('languages', models.CharField(choices=[('az', 'az'), ('ru', 'ru')], max_length=12, verbose_name='Dil')),
                ('motto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.motto', verbose_name='Deviz')),
            ],
            options={
                'verbose_name': 'Deviz tərcümələri',
            },
        ),
    ]
