# Generated by Django 5.2.10 on 2026-01-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='is_center_background_image',
            field=models.BooleanField(default=False, verbose_name='Ana səhifədəki ikinci arxa plan şəkli'),
        ),
    ]
