# Generated by Django 5.2.9 on 2025-12-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_add_missing_bloq_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='is_bloq_background_image',
            field=models.BooleanField(default=False, verbose_name='Bloq səhifəsi üçün arxa plan şəkli'),
        ),
    ]
