# Generated by Django 5.2.7 on 2025-11-12 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_remove_specialproject_is_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='is_background_image',
        ),
        migrations.AddField(
            model_name='image',
            name='is_about_page_background_image',
            field=models.BooleanField(default=False, verbose_name='Haqqımızda sehifesi üçün arxa plan şəkli'),
        ),
        migrations.AddField(
            model_name='image',
            name='is_calculator_page_background_image',
            field=models.BooleanField(default=False, verbose_name='Calculator sehifesi üçün arxa plan şəkli'),
        ),
        migrations.AddField(
            model_name='image',
            name='is_home_page_background_image',
            field=models.BooleanField(default=False, verbose_name='Ana sehifesi üçün arxa plan şəkli'),
        ),
        migrations.AddField(
            model_name='image',
            name='is_review_page_background_image',
            field=models.BooleanField(default=False, verbose_name='Comment elave et sehifesi üçün arxa plan şəkli'),
        ),
    ]
