# Generated by Django 5.2.11 on 2026-02-15 17:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_image_is_center_background_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialproject',
            options={'ordering': ('-created_at',), 'verbose_name': 'Tərəfdaş', 'verbose_name_plural': 'Tərəfdaşlar'},
        ),
        migrations.AlterModelOptions(
            name='specialprojecttranslation',
            options={'verbose_name': 'Tərəfdaş tərcüməsi', 'verbose_name_plural': 'Tərəfdaşlar tərcümələri'},
        ),
        migrations.AlterField(
            model_name='specialproject',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Tərəfdaş aktivliyi'),
        ),
        migrations.AlterField(
            model_name='specialprojecttranslation',
            name='description',
            field=models.CharField(max_length=350, validators=[django.core.validators.MaxLengthValidator(2000)], verbose_name='Tərəfdaş haqqında məlumat'),
        ),
        migrations.AlterField(
            model_name='specialprojecttranslation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='services.specialproject', verbose_name='Tərəfdaş'),
        ),
    ]
