# Generated by Django 5.2.7 on 2025-11-03 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_specialproject_alter_servicetranslation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='is_backgorund_image',
            field=models.BooleanField(default=False, verbose_name='Sayt üçün arxa plan şəkli'),
        ),
    ]
