# Generated by Django 5.2.8 on 2025-11-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_about_options_alter_abouttranslation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone_three',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefon'),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_two',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefon'),
        ),
    ]
