# Generated by Django 5.2.7 on 2025-11-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_motto_mottotranslation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Ünvan')),
                ('phone', models.CharField(max_length=50, verbose_name='Telefon')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('gmail', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Gmail')),
                ('social_1', models.URLField(blank=True, null=True, verbose_name='Sosial şəbəkə 1')),
                ('social_2', models.URLField(blank=True, null=True, verbose_name='Sosial şəbəkə 2')),
                ('social_3', models.URLField(blank=True, null=True, verbose_name='Sosial şəbəkə 3')),
            ],
            options={
                'verbose_name': 'Əlaqə',
                'verbose_name_plural': 'Əlaqələr',
            },
        ),
        migrations.AlterModelOptions(
            name='motto',
            options={'verbose_name': 'Devizlər'},
        ),
    ]
