# Generated by Django 5.2.7 on 2025-11-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_price_alter_servicevariant_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_premium',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Premium'),
        ),
        migrations.AddField(
            model_name='service',
            name='is_vip',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Vip'),
        ),
    ]
