# Generated by Django 5.2.7 on 2025-11-06 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_is_premium_service_is_vip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicevariant',
            name='type_name',
        ),
        migrations.CreateModel(
            name='ServiceVariantTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languages', models.CharField(choices=[('az', 'az'), ('ru', 'ru')], max_length=12)),
                ('name', models.CharField(max_length=50, verbose_name='Növ adı')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='services.servicevariant', verbose_name='Növ')),
            ],
            options={
                'verbose_name': 'Növ ad tərcüməsi',
                'verbose_name_plural': 'Növ ad tərcümələri',
            },
        ),
    ]
