# Generated by Django 5.2.11 on 2026-02-15 17:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_specialproject_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleevent',
            name='website_sale',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Saytdan gelen endirim faizi'),
        ),
    ]
