# Generated by Django 5.2.7 on 2025-11-03 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_image_is_backgorund_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='is_backgorund_image',
            new_name='is_background_image',
        ),
    ]
