# Generated by Django 5.2.9 on 2025-12-29 19:35

import ckeditor.fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_image_is_bloq_background_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloqtranslation',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, max_length=10000, null=True, validators=[django.core.validators.MaxLengthValidator(10000)], verbose_name='Bloq haqqında'),
        ),
    ]
