# Generated by Django 5.2.8 on 2025-11-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_contact_phone_three_contact_phone_two'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='phone_two',
        ),
        migrations.AddField(
            model_name='contact',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Whatsapp əlaqə nömrəsi'),
        ),
    ]
