# Generated by Django 5.2.7 on 2025-11-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_contact_alter_motto_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='social_1',
            new_name='social_one',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='social_3',
            new_name='social_three',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='social_2',
            new_name='social_two',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='gmail',
        ),
        migrations.AddField(
            model_name='contact',
            name='email_second',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email ikinci'),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_second',
            field=models.CharField(default=585655, max_length=50, verbose_name='Telefon ikinci'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
    ]
