# Generated by Django 5.2.8 on 2025-12-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_add_whatsapp_number_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='is_order_page_background_image',
            field=models.BooleanField(default=False, verbose_name='Sifariş sehifesi üçün arxa plan şəkli'),
        ),
    ]
