# Generated by Django 5.2.7 on 2025-11-06 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_remove_servicevariant_type_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='services',
        ),
    ]
