# Generated by Django 5.2.8 on 2025-12-29 16:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_image_is_order_page_background_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bloq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Url')),
                ('is_active', models.BooleanField(blank=True, default=False, null=True, verbose_name='Bloq aktivliyi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Bloq yaradılma tarixi')),
            ],
            options={
                'verbose_name': 'Bloq',
                'verbose_name_plural': 'Bloqlar',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AlterModelOptions(
            name='specialproject',
            options={'ordering': ('-created_at',), 'verbose_name': 'Əməkdaş', 'verbose_name_plural': 'Əməkdaşlar'},
        ),
        migrations.AlterModelOptions(
            name='specialprojecttranslation',
            options={'verbose_name': 'Əməkdaş tərcüməsi', 'verbose_name_plural': 'Əməkdaş  tərcümələri'},
        ),
        migrations.AlterField(
            model_name='specialproject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi'),
        ),
        migrations.AlterField(
            model_name='specialproject',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Əməkdaş aktivliyi'),
        ),
        migrations.AlterField(
            model_name='specialprojecttranslation',
            name='description',
            field=models.CharField(max_length=350, validators=[django.core.validators.MaxLengthValidator(2000)], verbose_name='Əməkdaş haqqında məlumat'),
        ),
        migrations.AlterField(
            model_name='specialprojecttranslation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='services.specialproject', verbose_name='Əməkdaş'),
        ),
        migrations.AddField(
            model_name='image',
            name='bloq',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='services.bloq', verbose_name='Bloq'),
        ),
        migrations.CreateModel(
            name='BloqTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Bloq növ adı')),
                ('languages', models.CharField(choices=[('az', 'az'), ('ru', 'ru')], max_length=12, verbose_name='Dil')),
                ('description', models.CharField(max_length=350, validators=[django.core.validators.MaxLengthValidator(2000)], verbose_name='Bloq haqqında başlanqıç cümləsi')),
                ('bloq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='services.bloq', verbose_name='Bloq')),
            ],
            options={
                'verbose_name': 'Bloq',
                'verbose_name_plural': 'Bloq tərcümələri',
            },
        ),
    ]
