# Generated by Django 5.2.7 on 2025-11-04 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_rename_is_backgorund_image_image_is_background_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about-image/', verbose_name='Haqqımızda arxa plan şəkili')),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_count', models.IntegerField(blank=True, null=True, verbose_name='Client sayı')),
                ('work_done_count', models.IntegerField(blank=True, null=True, verbose_name='Görülmüş iş sayı')),
                ('staff_count', models.IntegerField(blank=True, null=True, verbose_name='İşçi sayı')),
                ('achievement_count', models.IntegerField(blank=True, null=True, verbose_name='Nailiyyət sayı')),
            ],
            options={
                'verbose_name': 'Statistika',
                'verbose_name_plural': 'Statistikalar',
            },
        ),
        migrations.RenameField(
            model_name='servicetranslation',
            old_name='language',
            new_name='languages',
        ),
        migrations.RenameField(
            model_name='specialprojecttranslation',
            old_name='language',
            new_name='languages',
        ),
        migrations.CreateModel(
            name='AboutTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languages', models.CharField(choices=[('Azərbaycan', 'Azərbaycan'), ('Русский', 'Русский')], max_length=12, verbose_name='Dil')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.about', verbose_name='Haqqımızda')),
            ],
            options={
                'verbose_name': 'Haqqımızda tərcümələri',
            },
        ),
    ]
