# Generated by Django 5.2.7 on 2025-11-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_rename_social_1_contact_social_one_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_second',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefon ikinci'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='social_one',
            field=models.URLField(blank=True, null=True, verbose_name='Sosial şəbəkə 1 urli'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='social_three',
            field=models.URLField(blank=True, null=True, verbose_name='Sosial şəbəkə 3 urli'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='social_two',
            field=models.URLField(blank=True, null=True, verbose_name='Sosial şəbəkə 2 urli'),
        ),
    ]
