# Generated by Django 5.2.8 on 2025-11-29 10:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_remove_contact_phone_two_contact_whatsapp_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(240)], verbose_name='Mesaj'),
        ),
        migrations.AlterField(
            model_name='servicetranslation',
            name='description',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(4000)], verbose_name='Servis haqqında'),
        ),
    ]
