# Generated by Django 5.2.8 on 2025-11-29 13:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_review_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abouttranslation',
            name='highlight_description_one',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(200)], verbose_name='Sol üst ilk açıqlama'),
        ),
        migrations.AddField(
            model_name='abouttranslation',
            name='highlight_description_two',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(200)], verbose_name='Sol üst ikinci açıqlama'),
        ),
        migrations.AddField(
            model_name='abouttranslation',
            name='highlight_title_one',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Sol üst ilk başlıq'),
        ),
        migrations.AddField(
            model_name='abouttranslation',
            name='highlight_title_two',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Sol üst ikinci başlıq'),
        ),
        migrations.AddField(
            model_name='abouttranslation',
            name='main_title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Əsas başlıq'),
        ),
    ]
