# Generated by Django 5.2.7 on 2025-11-08 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_contact_phone_second_alter_contact_social_one_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mottotranslation',
            name='motto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='services.motto', verbose_name='Deviz'),
        ),
    ]
