# Generated by Django 5.2.8 on 2025-12-29 16:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_bloq_alter_specialproject_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloqtranslation',
            name='header',
            field=models.CharField(blank=True, max_length=250, null=True, validators=[django.core.validators.MaxLengthValidator(250)], verbose_name='Bloq haqqında başlanğıc cümləsi'),
        ),
        migrations.AlterField(
            model_name='bloqtranslation',
            name='description',
            field=models.CharField(blank=True, max_length=5000, null=True, validators=[django.core.validators.MaxLengthValidator(5000)], verbose_name='Bloq haqqında'),
        ),
    ]
