# Generated by Django 5.2.7 on 2025-11-04 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_about_statistics_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Servis', 'verbose_name_plural': 'Servislər'},
        ),
    ]
