# Generated by Django 5.2.11 on 2026-02-15 18:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_saleevent_website_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleevent',
            name='website_sale',
            field=models.FloatField(blank=True, default=5.0, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Saytdan gelen endirim faizi'),
        ),
    ]
