# Generated by Django 5.2.7 on 2025-11-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_remove_review_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='kv_metr',
            field=models.FloatField(blank=True, null=True, verbose_name='Kvadrat metr (m²)'),
        ),
        migrations.AddField(
            model_name='service',
            name='metr',
            field=models.FloatField(blank=True, null=True, verbose_name='Metr (m)'),
        ),
    ]
