# Generated by Django 5.2.7 on 2025-11-04 18:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_service_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='abouttranslation',
            name='description',
            field=models.TextField(default='asasfas', validators=[django.core.validators.MaxLengthValidator(2000)], verbose_name='Servis haqqında'),
            preserve_default=False,
        ),
    ]
