# Generated by Django 5.2.7 on 2025-11-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_service_kv_metr_service_metr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='kv_metr',
        ),
        migrations.RemoveField(
            model_name='service',
            name='metr',
        ),
        migrations.AddField(
            model_name='service',
            name='is_kv_metr',
            field=models.BooleanField(blank=True, null=True, verbose_name='Kvadrat metr (m²) ilə hesablanırsa'),
        ),
        migrations.AddField(
            model_name='service',
            name='is_metr',
            field=models.BooleanField(blank=True, null=True, verbose_name='Metr (m) ilə hesablanırsa'),
        ),
    ]
