# Generated by Django 5.2.7 on 2025-11-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_mottotranslation_motto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialproject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Lahiyə yaradılma tarixi'),
        ),
        migrations.AlterField(
            model_name='specialproject',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Lahiyə aktivliyi'),
        ),
    ]
