# Generated by Django 5.2.8 on 2025-11-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_abouttranslation_highlight_description_one_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abouttranslation',
            name='main_title',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Əsas başlıq'),
        ),
    ]
