# Generated by Django 5.2.7 on 2025-11-06 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_remove_service_kv_metr_remove_service_metr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicevariant',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='services.service', verbose_name='Servis üçün növlər'),
        ),
    ]
