# Generated by Django 5.2.7 on 2025-11-04 18:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_abouttranslation_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=32, verbose_name='Ad soyad')),
                ('phone_number', models.CharField(max_length=10, verbose_name='Mobil nömrə')),
                ('comment', models.TextField(validators=[django.core.validators.MaxLengthValidator(2000)], verbose_name='Mesaj')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Rəyin təsdiqlənməsi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Rəyin yaradılma tarixi')),
            ],
            options={
                'verbose_name': 'Rəy',
                'verbose_name_plural': 'Rəylər',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AlterField(
            model_name='abouttranslation',
            name='about',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='services.about', verbose_name='Haqqımızda'),
        ),
        migrations.AlterField(
            model_name='specialprojecttranslation',
            name='description',
            field=models.CharField(max_length=350, validators=[django.core.validators.MaxLengthValidator(2000)], verbose_name='Xüsusi layihə haqqında məlumat'),
        ),
    ]
