# Generated by Django 5.2.7 on 2025-11-08 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_specialproject_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialproject',
            name='is_completed',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Lahiyə tamamblanıb'),
        ),
        migrations.AddField(
            model_name='specialproject',
            name='is_contiune',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Lahiyə davam edir'),
        ),
    ]
