# Generated by Django 5.2.7 on 2025-11-08 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_specialproject_is_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialproject',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Lahiyə aktivliyi'),
        ),
        migrations.AlterField(
            model_name='specialproject',
            name='is_contiune',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Lahiyə davam edir'),
        ),
    ]
