# Generated by Django 5.2.7 on 2025-11-06 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_servicevariant_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetranslation',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='services.service', verbose_name='Servis'),
        ),
    ]
