# Generated by Django 5.2.7 on 2025-11-04 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_review_alter_abouttranslation_about_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='comment',
            new_name='text',
        ),
    ]
