# Generated by Django 5.2.7 on 2025-11-04 18:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_rename_comment_review_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='services',
            field=models.ManyToManyField(to='services.service', verbose_name='Rəy verilən servislər'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=32, verbose_name='Ad soyad')),
                ('phone_number', models.CharField(max_length=10, verbose_name='Mobil nömrə')),
                ('text', models.TextField(validators=[django.core.validators.MaxLengthValidator(2000)], verbose_name='Mesaj')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sifarişin verilmə tarixi')),
                ('services', models.ManyToManyField(to='services.service', verbose_name='Şifariş verilən servislər')),
            ],
            options={
                'verbose_name': 'Sifariş',
                'verbose_name_plural': 'Sifarişlər',
                'ordering': ('-created_at',),
            },
        ),
    ]
