# Generated by Django 5.2.7 on 2025-11-06 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_alter_servicetranslation_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetranslation',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='services.service', verbose_name='Servis'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicevarianttranslation',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='services.servicevariant', verbose_name='Növ'),
        ),
    ]
