# Generated by Django 5.2.7 on 2025-11-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_alter_specialproject_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='email_second',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone_second',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='social_one',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='social_three',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='social_two',
        ),
        migrations.AddField(
            model_name='contact',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='linkedn',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='tiktok',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
    ]
