# Generated by Django 5.2.7 on 2025-11-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_alter_servicetranslation_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicevarianttranslation',
            name='languages',
            field=models.CharField(blank=True, choices=[('az', 'az'), ('ru', 'ru')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='servicevarianttranslation',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Növ adı'),
        ),
    ]
