# Generated by Django 5.2.7 on 2025-11-09 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_remove_contact_email_second_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='service',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='services.service', verbose_name='Service'),
            preserve_default=False,
        ),
    ]
