# Generated by Django 5.2.7 on 2025-11-04 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_review_services_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Şəkil'),
        ),
    ]
