# Generated by Django 5.2.7 on 2025-11-04 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_alter_image_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Statistics',
            new_name='Statistic',
        ),
    ]
