# Generated by Django 5.2.7 on 2025-11-09 15:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_alter_review_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(140)], verbose_name='Mesaj'),
        ),
    ]
