# Generated by Django 5.2.7 on 2025-11-05 15:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_rename_statistics_statistic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialproject',
            options={'ordering': ('-created_at',), 'verbose_name': 'Xüsusi Lahiyə', 'verbose_name_plural': 'Xüsusi Lahiyələr'},
        ),
        migrations.AddField(
            model_name='specialproject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Servis yaradılma tarixi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specialproject',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Servis aktivliyi'),
        ),
        migrations.AlterField(
            model_name='abouttranslation',
            name='languages',
            field=models.CharField(choices=[('az', 'az'), ('ru', 'ru')], max_length=12, verbose_name='Dil'),
        ),
        migrations.AlterField(
            model_name='servicetranslation',
            name='languages',
            field=models.CharField(choices=[('az', 'az'), ('ru', 'ru')], max_length=12),
        ),
        migrations.AlterField(
            model_name='specialprojecttranslation',
            name='languages',
            field=models.CharField(choices=[('az', 'az'), ('ru', 'ru')], max_length=12, verbose_name='Dil'),
        ),
    ]
