# Generated by Django 5.2.7 on 2025-11-10 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_alter_review_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Aksiya Adı')),
                ('sale', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Endirim Faizi')),
                ('measure_type', models.CharField(choices=[('m', 'm'), ('m2', 'm2'), ('kg', 'kg'), ('unit', 'unit')], max_length=10, verbose_name='Ölçü Növü')),
                ('min_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Endirimin aktif olacağı dəyər')),
                ('active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='services.service', verbose_name='Servis')),
            ],
            options={
                'verbose_name': 'Endirim kampaniyası',
                'verbose_name_plural': 'Endirim kampaniyaları',
            },
        ),
    ]
