# Generated by Django 5.2.7 on 2025-11-06 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_alter_specialproject_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(max_length=12, unique=True, verbose_name='Mobil nömrə'),
        ),
        migrations.AlterField(
            model_name='review',
            name='phone_number',
            field=models.CharField(max_length=12, verbose_name='Mobil nömrə'),
        ),
    ]
