# Generated by Django 5.2.7 on 2025-11-10 13:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_saleevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='sale',
        ),
        migrations.AlterField(
            model_name='saleevent',
            name='sale',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Endirim faizi'),
        ),
    ]
