# Generated by Django 5.2.7 on 2025-11-10 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_remove_service_sale_alter_saleevent_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleEventTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languages', models.CharField(blank=True, choices=[('az', 'az'), ('ru', 'ru')], max_length=12, null=True, verbose_name='Dillər')),
                ('name', models.CharField(max_length=255, verbose_name='Aksiya Adı')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='services.saleevent', verbose_name='Endirim eventi')),
            ],
            options={
                'verbose_name': 'Endirim kampaniyası təcüməsi',
                'verbose_name_plural': 'Endirim kampaniyaları tərcümələri',
            },
        ),
    ]
