# Generated by Django 5.2.7 on 2025-11-10 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_saleeventtranslation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleevent',
            name='name',
        ),
    ]
