# Generated by Django 5.2.7 on 2025-11-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_remove_saleevent_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleevent',
            name='measure_type',
        ),
        migrations.RemoveField(
            model_name='service',
            name='is_kq',
        ),
        migrations.RemoveField(
            model_name='service',
            name='is_kv_metr',
        ),
        migrations.RemoveField(
            model_name='service',
            name='is_metr',
        ),
        migrations.RemoveField(
            model_name='service',
            name='is_number',
        ),
        migrations.AddField(
            model_name='service',
            name='measure_type',
            field=models.CharField(choices=[('m', 'm'), ('m2', 'm2'), ('kg', 'kg'), ('ədəd', 'ədəd')], default=1, max_length=10, verbose_name='Ölçü Növü'),
            preserve_default=False,
        ),
    ]
