# Generated by Django 5.2.7 on 2025-11-10 14:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_remove_saleevent_measure_type_remove_service_is_kq_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleeventtranslation',
            name='description',
            field=models.TextField(default=4, validators=[django.core.validators.MaxLengthValidator(200)], verbose_name='Aksiya haqqında'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='saleeventtranslation',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Aksiya Adı'),
        ),
    ]
