# Generated by Django 5.2.7 on 2025-11-10 14:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_saleeventtranslation_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleeventtranslation',
            name='description',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(350)], verbose_name='Aksiya haqqında'),
        ),
    ]
