LANG_AZ = 'az'
LANG_RUS = 'ru'

LANGUAGES = [
    (LANG_AZ, LANG_AZ),
    (LANG_RUS, LANG_RUS)
]


MEASURE_M = 'm'
MEASURE_M_DOUBLE = 'm2'
MEASURE_KG = 'kg'
MEASURE_UNIT = 'ədəd'

MEASURE_TYPE_CHOICES = [
    (MEASURE_M, MEASURE_M),
    (MEASURE_M_DOUBLE, MEASURE_M_DOUBLE),
    (MEASURE_KG, MEASURE_KG),
    (MEASURE_UNIT, MEASURE_UNIT),
]